name: flutter_worksmart_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^8.0.0
  intl: ^0.20.2
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  camera: ^0.11.3
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  file_picker: ^10.3.10
  image_picker: ^1.2.1
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    # - assets/animations/
